version: "3.9"
services:
  frontend:
    restart: always
    build: ./frontend/.
    ports: 
      - "3000:3000"

  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "tododb"
      POSTGRES_USER: "usertodo"
      POSTGRES_PASSWORD: "passtodo"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "tododb", "-U", "usertodo"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    depends_on: 
      database:
       condition: service_healthy
    build: ./backend/.
    restart: always
    ports:
      - "8080:8080"
